name: betchya_frontend
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^9.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  go_router: ^17.1.0
  intl: ^0.20.2
  supabase_flutter: ^2.10.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3
  very_good_analysis: ^6.0.0

flutter_native_splash:
  color: "#2C1D57"
  image: assets/images/home_final.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
